### ISSUE TITLE
Multi-Commander support issues

### ISSUE THREAD

**Issue by ghost** [RocketMan1988/EDMC-Passport-System#1]
EMDC 4.0.6, Win 10 home 1903, E:D Fleet Carrier Update 4, EDPS load.py version posted on discord on 28-AUG-2020

Set up EDPS for my main account Cometborne, imported local journals, EDPS correctly detected that I had docked on my own FC.

Quit E:D to desktop, re-launched with an alt account, did not set up EDPS for it.  Flew to the nearest FC, docked, received the following message:
![image](https://user-images.githubusercontent.com/25147462/91553500-ccfaa580-e92d-11ea-87af-a714b74af995.png)

This indicates that EDPS is getting log messages from the currently active journal of my alt, but either did not notice the commander switch, did not re-initialize correctly, or failed to recognize the lack of EDPS set-up for the alt, or similar. In any case, it tried to submit a docked event for my alt, and something downstream failed miserably.

**Comment by ghost** [comment]
Addendum: After a restart of EDMC while the game was not running, I get the following message:

![image](https://user-images.githubusercontent.com/25147462/91563319-efe18580-e93e-11ea-84cf-b668cb884ef2.png)

This confirms my suspicion that the initialization of the commander is only done at EDMC startup and that the use case: "Switching commanders while EDMC is running" was not taken into account.

Side note: All the above was done using the "harmless" variant of quitting to desktop and only having one instance active at a time.  It is possible to have several instances/commanders active at the same time, which poses additional challenges.  EDMC itself handles this just fine, but most plugins struggle with this situation.

**Comment by ghost** [comment]
Addendum: Even after switching back to my main account, I keep getting the above error message until I first log in to E:D to create a new journal, quit E:D, and then restart EDMC.

**Comment by RocketMan1988** [comment]
Multi-commander support should be there now in release 0.2v :) 

Let me know if you have anymore issues and I will reopen the issue.
