### ISSUE TITLE
No EDPS tab in EDMC Settings

### ISSUE THREAD

**Issue by panikpansen** [RocketMan1988/EDMC-Passport-System#12]
I'm following the installation guide to get this plugin running, but the tab to enter my EDPS information (including my API key) does not appear as in the screenshots. I may be missing something super obvious here - any advice?

I've installed (downloaded - unzipped - moved) the plugin, and after a restart EDMC seems to recognise the plugin: In the main panel lines for "Passports:" and "EDPS:" have been added, and in Settings > Plugins the Plugin is listed as enabled.

In EDMC > Settings no new tab for EDPS has appeared though, and I can't find another place to enter the API key. This is for EDMC version 5.1.3+ 1a0b4ae and plugin version 1.3 beta. 

Thanks for your help =)

edit: resolved now, although I don't know how. I closed everything and tried again a few hours later. Now it all works, the tab appeared and I could enter my API key.

**Comment by RocketMan1988** [comment]
I saw this in testing too. When you first open up the tool it creates some required settings and saves them to a file. That process takes some time, so opening/closing/waiting will typically solve your issue. :)

**Comment by RocketMan1988** [comment]
Closing issue
