### ISSUE TITLE
Wrong patches

### ISSUE THREAD

**Issue by ragnarblackmane** [RocketMan1988/EDMC-Passport-System#2]
![Huginn](https://user-images.githubusercontent.com/71211822/93014809-8b682c80-f5b4-11ea-9b75-14e2f8aefc51.png)
![Muninn](https://user-images.githubusercontent.com/71211822/93014810-8c995980-f5b4-11ea-83c3-4188fbcd97ea.png)

Hi, here are the patches for NECFC Huginn and NECFC Muninn

**Comment by RocketMan1988** [comment]
Thanks! 

I updated the two patches on the site. :)
