### ISSUE TITLE
DSSA Somdy

### ISSUE THREAD

**Issue by spinnelein** [RocketMan1988/EDMC-Passport-System#4]
DSSA Somdy.
System is located at Lyed YJ-I d9-0 

does not properly register. 
[somdy.log](https://github.com/RocketMan1988/EDMC-Passport-System/files/5506895/somdy.log)

**Comment by spinnelein** [comment]
Add Walk in the Shadows to the "stations not working for EDPS" list. The carrier number is k0(zero)v-LHW, but it's on EDPS as kO(Oh)v-LH

**Comment by RocketMan1988** [comment]
Looks like it was fixed by a pervious commit. (Probably by yourself - Thanks)
