### ISSUE TITLE
The settings tab does not appear

### ISSUE THREAD

**Issue by luilegeant** [RocketMan1988/EDMC-Passport-System#5]
Hello,

I'm trying the beta 1.3. the plugin seems to load fine, I can see the following in EDMC
```
Passports: 0 of 82
EDPS: Connected to EDPS 1.3!
```
But once I open the EDMC settings I can't find the tab for EDPS.

The logs contain following when opening the settings:
```
2020-11-27 22:14:30.902 - ERROR - plug.Plugin.get_prefs:165: Failed for Plugin "EDPS"
Traceback (most recent call last):
  File "plug.pyc", line 160, in get_prefs
  File "C:\Users\nicolas\AppData\Local\EDMarketConnector\plugins\EDMC-Passport-System-1.3\load.py", line 315, in plugin_prefs
    config.set('edpscmder', cmdr)
  File "config.pyc", line 259, in set
NotImplementedError
```

Application used: EDMC 4.1.4 (installed via the msi) and the beta 1.3 of EDPS.

**Comment by luilegeant** [comment]
The next day, understand "after restarting the computer" the tab appeared.

If you don't want to follow up this issue, you may close this ticket, I'll report if anything else occurs.

**Comment by RocketMan1988** [comment]
There seems to be an issue on some machines where the plugin doesn't work until it loads up, initializes, and then you restart EDMC. If I get a bunch of more reports of this I'll look into it. Thank you for documenting your logs so well. Closing for the time being.
