### ISSUE TITLE
Missing DSSA carriers

### ISSUE THREAD

**Issue by chennin** [RocketMan1988/EDMC-Passport-System#8]
https://inara.cz/station/183920/
https://inara.cz/galaxy-station/211128/
https://inara.cz/station/214435/
https://inara.cz/station/192997/

I have visited all of them in the past month.

https://www.edps.dev/?commander=Floor%20Jansen

**Comment by RocketMan1988** [comment]
I'll look into this. Thank you for the ping. 👍

**Comment by chennin** [comment]
This may have been fixed on 21 August by FlyDangerous: my count went up when I rescanned journals. Though I didn't specifically test each report here

https://discord.com/channels/164411426939600896/749701520865493012/878793109557903440 (EDCD)
