### ISSUE TITLE
Typo's / changed ids in carrier callsigns 

### ISSUE THREAD

**Issue by jlabeeuw** [RocketMan1988/EDMC-Passport-System#9]
After executing the DSSA journey, I noticed a couple of changes / typos in the FCs List as obtained via https://www.edps.dev/FCs.json :

J4F-01X ==> H2X-6XV  &   SCAULOU SZ-M D8-911 ==>  Scaulou SZ-M d8-911 (or check lower case of system names)
X5W-63Z ==> JLL-BQZ
LZQ-24Q. ==> LZQ-24Q
XZ4-NXF ==> XZH-NXF
KOV-LHW ==> K0V-LHW

My log entries for lookup:
Journal.210726225607.01.log:{ "timestamp":"2021-07-26T22:21:10Z", "event":"Docked", "StationName":"H2X-6XV", "StationType":"FleetCarrier", "StarSystem":"Scaulou SZ-M d8-911", "SystemAddress":31310789727435, "MarketID":3705563904, "StationFaction":{ "Name":"FleetCarrier" }, "StationGovernment":"$government_Carrier;", "StationGovernment_Localised":"Private Ownership ", "StationServices":[ "dock", "autodock", "commodities", "contacts", "exploration", "outfitting", "crewlounge", "rearm", "refuel", "repair", "shipyard", "engineer", "flightcontroller", "stationoperations", "stationMenu", "carriermanagement", "carrierfuel", "socialspace" ], "StationEconomy":"$economy_Carrier;", "StationEconomy_Localised":"Private Enterprise", "StationEconomies":[ { "Name":"$economy_Carrier;", "Name_Localised":"Private Enterprise", "Proportion":1.000000 } ], "DistFromStarLS":1592.868593 }

Journal.210715104651.01.log:{ "timestamp":"2021-07-15T14:03:34Z", "event":"Docked", "StationName":"JLL-BQZ", "StationType":"FleetCarrier", "StarSystem":"Dryau Aec JF-A d11", "SystemAddress":390229673091, "MarketID":3703941120, "StationFaction":{ "Name":"FleetCarrier" }, "StationGovernment":"$government_Carrier;", "StationGovernment_Localised":"Private Ownership ", "StationServices":[ "dock", "autodock", "commodities", "contacts", "exploration", "crewlounge", "rearm", "refuel", "repair", "shipyard", "engineer", "flightcontroller", "stationoperations", "stationMenu", "carriermanagement", "carrierfuel", "socialspace" ], "StationEconomy":"$economy_Carrier;", "StationEconomy_Localised":"Private Enterprise", "StationEconomies":[ { "Name":"$economy_Carrier;", "Name_Localised":"Private Enterprise", "Proportion":1.000000 } ], "DistFromStarLS":1340.596164 }

Journal.210715234551.01.log: { "timestamp":"2021-07-15T22:55:56Z", "event":"Docked", "StationName":"LZQ-24Q", "StationType":"FleetCarrier", "StarSystem":"Lyed YJ-I d9-0", "SystemAddress":12792627923, "MarketID":3700951808, "StationFaction":{ "Name":"FleetCarrier" }, "StationGovernment":"$government_Carrier;", "StationGovernment_Localised":"Private Ownership ", "StationServices":[ "dock", "autodock", "commodities", "contacts", "exploration", "outfitting", "crewlounge", "rearm", "refuel", "repair", "shipyard", "engineer", "flightcontroller", "stationoperations", "stationMenu", "carriermanagement", "carrierfuel" ], "StationEconomy":"$economy_Carrier;", "StationEconomy_Localised":"Private Enterprise", "StationEconomies":[ { "Name":"$economy_Carrier;", "Name_Localised":"Private Enterprise", "Proportion":1.000000 } ], "DistFromStarLS":0.000000 }

Journal.210720201148.01.log:{ "timestamp":"2021-07-20T21:03:10Z", "event":"Docked", "StationName":"XZH-NXF", "StationType":"FleetCarrier", "StarSystem":"Floalk QQ-Q c20-2", "SystemAddress":606697234098, "MarketID":3700347392, "StationFaction":{ "Name":"FleetCarrier" }, "StationGovernment":"$government_Carrier;", "StationGovernment_Localised":"Private Ownership ", "StationServices":[ "dock", "autodock", "commodities", "contacts", "exploration", "outfitting", "crewlounge", "rearm", "refuel", "repair", "shipyard", "engineer", "flightcontroller", "stationoperations", "stationMenu", "carriermanagement", "carrierfuel", "socialspace" ], "StationEconomy":"$economy_Carrier;", "StationEconomy_Localised":"Private Enterprise", "StationEconomies":[ { "Name":"$economy_Carrier;", "Name_Localised":"Private Enterprise", "Proportion":1.000000 } ], "DistFromStarLS":999.692646 }

Journal.210708002208.01.log:{ "timestamp":"2021-07-07T22:41:43Z", "event":"Docked", "StationName":"K0V-LHW", "StationType":"FleetCarrier", "StarSystem":"Plae Chreou HK-A d6", "SystemAddress":214404471811, "MarketID":3701456640, "StationFaction":{ "Name":"FleetCarrier" }, "StationGovernment":"$government_Carrier;", "StationGovernment_Localised":"Private Ownership ", "StationServices":[ "dock", "autodock", "commodities", "contacts", "exploration", "outfitting", "crewlounge", "rearm", "refuel", "repair", "shipyard", "engineer", "flightcontroller", "stationoperations", "stationMenu", "carriermanagement", "carrierfuel" ], "StationEconomy":"$economy_Carrier;", "StationEconomy_Localised":"Private Enterprise", "StationEconomies":[ { "Name":"$economy_Carrier;", "Name_Localised":"Private Enterprise", "Proportion":1.000000 } ], "DistFromStarLS":954.025373 }

**Comment by RocketMan1988** [comment]
Fixed typos with latest commit to the webpage git repository.  Thanks for letting me know about this. Let me know if anything is not still working. :)
